// <auto-generated />
using ECommerceApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230102212739_SeedMoreData")]
    partial class SeedMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceApp.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Glass",
                            Url = "glass"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bakelser",
                            Url = "bakelser"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bröd",
                            Url = "bröd"
                        });
                });

            modelBuilder.Entity("ECommerceApp.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Gräddig och god saffransglass som också blir lysande gul av saffranet.",
                            ImageUrl = "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_217210/cf_259/hemmagjord_vaniljglass.jpg",
                            Price = 85.00m,
                            Title = "SaffransGlass"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Äkta pistageglass är en av mina absoluta favoriter när det kommer till glass. Den här hemmagjorda varianten blev helt perfekt i både smak och konsistens.",
                            ImageUrl = "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_217210/cf_259/hemmagjord_vaniljglass.jpg",
                            Price = 60.0m,
                            Title = "PistageGlass"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Glass med äkta vanilj – gör egen vaniljglass med glassmaskin! Grädde, mjölk och äggulor utgör basen till glassen som får smak av socker, vaniljstång och salt.",
                            ImageUrl = "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_217210/cf_259/hemmagjord_vaniljglass.jpg",
                            Price = 30.0m,
                            Title = "VaniljGlass"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Crunchy Choklad Cookies!!",
                            ImageUrl = "https://bakingamoment.com/wp-content/uploads/2016/09/IMG_0316-chocolate-chip-cookies-1-720x720.jpg",
                            Price = 30.0m,
                            Title = "Choklad Cookie"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Krispiga Kolasnittar!",
                            ImageUrl = "https://ingmar.app/blog/wp-content/uploads/2015/12/kolasnittar2.jpg",
                            Price = 30.0m,
                            Title = "Kola Cookies"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Vårt klassiska recept på Vetebullar/Kanelbullar/Vetebröd, samma recept som återfinns på våra vetemjöls-förpackningar!",
                            ImageUrl = "https://www.kungsornen.se/467791/siteassets/2.-recept/saftigaste-kanelbullarna.jpg?maxwidth=1440",
                            Price = 30.0m,
                            Title = "Kanelbullar"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "GUDOMLIGT GODA SAFFRANSBULLAR Riktigt, riktigt saftiga och goda saffransbullar! Smörkrämsfyllningen gör bullarna extra saftiga & goda!",
                            ImageUrl = "https://ingmar.app/blogg/wp-content/uploads/2020/11/Saffransbullar.jpg",
                            Price = 30.0m,
                            Title = "Saffransbullar"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "lkdfkljdsjkfdlkjfdjlsk",
                            ImageUrl = "https://ingmar.app/blogg/wp-content/uploads/2020/11/Saffransbullar.jpg",
                            Price = 30.0m,
                            Title = "SaffransLimpa"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "-",
                            ImageUrl = "https://ingmar.app/blogg/wp-content/uploads/2020/11/Saffransbullar.jpg",
                            Price = 30.0m,
                            Title = "Bananbröd"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "földsölkfdöklfölsdöklsfd",
                            ImageUrl = "https://ingmar.app/blogg/wp-content/uploads/2020/11/Saffransbullar.jpg",
                            Price = 30.0m,
                            Title = "BarbariBröd"
                        });
                });

            modelBuilder.Entity("ECommerceApp.Shared.Product", b =>
                {
                    b.HasOne("ECommerceApp.Shared.Category", "Catergory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catergory");
                });
#pragma warning restore 612, 618
        }
    }
}
